"""empty message

Revision ID: 2e976fee87ef
Revises: b6085a3b1468
Create Date: 2020-04-24 11:20:21.749637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e976fee87ef'
down_revision = 'b6085a3b1468'
branch_labels = None
depends_on = None


def upgrade():
    gender = postgresql.ENUM('F', 'M', 'X', name='gender')
    gender.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swimmers', sa.Column('birth_year', sa.Integer(), nullable=False))
    op.add_column('swimmers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('swimmers', sa.Column('gender', sa.Enum('F', 'M', 'X', name='gender'), nullable=False))
    op.add_column('swimmers', sa.Column('last_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swimmers', 'last_name')
    op.drop_column('swimmers', 'gender')
    op.drop_column('swimmers', 'first_name')
    op.drop_column('swimmers', 'birth_year')
    # ### end Alembic commands ###

    gender = postgresql.ENUM('F', 'M', 'X', name='gender')
    gender.drop(op.get_bind())
