"""empty message

Revision ID: 4cd148cf9cc8
Revises: 5f11f89469c2
Create Date: 2020-04-24 12:30:07.080936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cd148cf9cc8'
down_revision = '5f11f89469c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swimmer_id', sa.Integer(), nullable=False),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Enum('LCM', 'SCM', 'SCY', name='course'), nullable=False),
    sa.Column('distance', sa.Integer(), sa.CheckConstraint('distance IN (25, 50, 100, 200, 400, 800, 1500)'), nullable=False), # adjusted to include CheckConstraint
    sa.Column('stroke', sa.Enum('Back', 'Breast', 'Fly', 'Free', 'IM', name='stroke'), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.ForeignKeyConstraint(['swimmer_id'], ['swimmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
